"""VBScript execution via cscript.exe.

This module provides a component responsible for executing VBScripts designed
to control a specific SAP session via cscript.exe.

The VBScriptRunner class handles:

- Synchronous script execution
- Asynchronous script execution via a thread pool
- Timeout management
- Optional validation of files produced by scripts
- Injection of a SAP-compatible header for explicit connection and session
  identification
- Optional addition of an Excel workbook close instruction
- Guarding against concurrent execution that would corrupt a shared script file
- Configurable text encoding for reading/writing script files

This service constitutes the technical execution layer for external scripts
used in SAP automation.
"""

from __future__ import annotations

import subprocess
from collections.abc import Callable
from concurrent.futures import Future, ThreadPoolExecutor
from pathlib import Path
from textwrap import dedent
from threading import Lock
from typing import Any

from .exceptions import SAPScriptExecutionException
from .utils import resolve_logger


class VBScriptRunner:
    """Executes VBScripts for SAP synchronously or asynchronously.

    This class encapsulates the call to cscript.exe to launch VBScripts while
    passing them the information necessary to identify the target SAP session
    and associated connection.

    It also enables:

    - Controlling the number of scripts executed in parallel
    - Detecting missing scripts
    - Managing return errors and timeout violations
    - Validating a file generated by the script if a validator is provided
    - Completing the script with instructions necessary for targeting the correct
      connection and SAP session

    Note:
        The source VBS script is modified **in place, on disk** the first
        time it runs (its SAP header is rewritten and, if applicable, an
        Excel-closing instruction is appended). This is a one-time,
        idempotent migration for a given file - subsequent calls detect the
        already-patched header and skip re-patching.

    Warning:
        Because the patch step reads and rewrites the script file directly,
        running the **same `script_path`** concurrently from two different
        calls (e.g. two sessions) could interleave reads/writes and corrupt
        the script. This is actively prevented: `execute` tracks every
        script path currently being processed (via `_active_scripts`,
        resolved to an absolute path so different string spellings of the
        same file are recognized as the same file) and immediately raises
        `SAPScriptExecutionException` if a second concurrent call targets a
        script that is already in flight, instead of allowing the two writes
        to race. If you need the same script logic running in parallel on
        multiple sessions, keep a separate copy of the `.vbs` file per
        session - each copy is then tracked independently.

    Attributes:
        SCRIPT_OLD_HEADER (str): Standard SAP header for older scripts.
        SCRIPT_NEW_HEADER (str): Patched header supporting session/connection indexing.
        _executor (ThreadPoolExecutor): Thread pool for async operations.
        _file_validator (Callable[[Path], None] | None): File validation callback.
        _logger (Callable[[str, bool], None]): The logging function.
        _default_encoding (str): Encoding used when a call to `execute` does
            not specify one explicitly.
        _active_sessions (set[tuple[int, int]]): Registry of sessions currently running a script.
        _active_sessions_lock (Lock): Thread safety lock for the session registry.
        _active_scripts (set[Path]): Registry of resolved script paths currently
            being patched/executed, used to detect and reject unsafe concurrent
            use of the same file.
        _active_scripts_lock (Lock): Thread safety lock for the script-path registry.

    Example:
        ```python
        runner = VBScriptRunner(max_workers=4)
        output = runner.execute(
            script_path=Path("script.vbs"),
            session_index=0,
            connection_index=0,
            timeout=120,
        )
        ```

        Using a non-default encoding for a script known to be saved as UTF-8:

        ```python
        output = runner.execute(
            script_path=Path("script_utf8.vbs"),
            session_index=0,
            connection_index=0,
            encoding="utf-8-sig",
        )
        ```
    """

    SCRIPT_OLD_HEADER = dedent("""\
        If Not IsObject(application) Then
           Set SapGuiAuto  = GetObject("SAPGUI")
           Set application = SapGuiAuto.GetScriptingEngine
        End If
        If Not IsObject(connection) Then
           Set connection = application.Children(0)
        End If
        If Not IsObject(session) Then
           Set session    = connection.Children(0)
        End If
        If IsObject(WScript) Then
           WScript.ConnectObject session,    "on"
           WScript.ConnectObject application, "on"
        End If""")

    SCRIPT_NEW_HEADER = dedent("""\
        Dim SapGuiAuto, application, connection, session
        Dim sessionIndex, connectionIndex
        sessionIndex = CLng(WScript.Arguments(0))
        connectionIndex = CLng(WScript.Arguments(1))
        If Not IsObject(application) Then
           Set SapGuiAuto = GetObject("SAPGUI")
           Set application = SapGuiAuto.GetScriptingEngine
        End If
        If Not IsObject(connection) Then
           Set connection = application.Children(CLng(connectionIndex))
        End If
        If Not IsObject(session) Then
           Set session = connection.Children(CLng(sessionIndex))
        End If
        If IsObject(WScript) Then
           WScript.ConnectObject session, "on"
           WScript.ConnectObject application, "on"
        End If""")

    def __init__(
        self,
        *,
        max_workers: int = 4,
        file_validator: Callable[[Path], None] | None = None,
        logger: Callable[[str, bool], None] | None = None,
    ) -> None:
        """Initializes the VBScript runner.

        Args:
            max_workers: Maximum number of threads used for asynchronous script
                execution. Defaults to 4.
            file_validator: Validation function called on the file generated by
                the script, if applicable.
            logger: Logging function. If None, :func:`~pysapgui.utils.default_logger`
                is used. All output is subject to the library-wide switch
                controlled by :func:`pysapgui.set_logging_enabled`.

        Raises:
            ValueError: If `encoding` is not a valid/known text codec name.
        """
        self._executor = ThreadPoolExecutor(max_workers=max_workers)
        self._file_validator = file_validator
        self._logger = resolve_logger(logger)
        self._active_sessions: set[tuple[int, int]] = set()
        self._active_sessions_lock = Lock()
        self._active_scripts: set[Path] = set()
        self._active_scripts_lock = Lock()

    def _read_script_text(self, script_path: Path, encoding: str) -> str:
        """Reads a script file's text content using a specific, strict encoding.

        Unlike a permissive read (e.g. `errors="ignore"`), this uses strict
        error handling: if the file's actual bytes are not valid under
        `encoding`, decoding fails loudly instead of silently dropping or
        mangling characters.

        Args:
            script_path: Path to the `.vbs` file to read.
            encoding: The text encoding to decode the file with.

        Returns:
            str: The decoded file content.

        Raises:
            SAPScriptExecutionException: If the file cannot be decoded using
                the given encoding, with guidance to pass a different
                `encoding` value.
        """
        try:
            return script_path.read_text(encoding=encoding)
        except (UnicodeDecodeError, UnicodeError) as exc:
            raise SAPScriptExecutionException(
                f"Failed to decode script '{script_path}' using encoding "
                f"'{encoding}': {exc}. The file is likely saved with a "
                "different encoding than expected - pass the correct "
                "`encoding` to `execute()` / `ScriptExecutionRequest` or to "
                "`VBScriptRunner(encoding=...)`.",
                critical=True,
            ) from exc

    def _patch_sap_vbs_script(self, script_path: Path, encoding: str) -> None:
        """Updates a SAP VBS script header to use WScript.Arguments.

        Checks if the script has been patched to retrieve indices from command
        line arguments. If not, replaces the old header with the new one.

        Args:
            script_path: Path to the VBS script to modify.
            encoding: Text encoding used to read and re-write the script file.

        Raises:
            ValueError: If the expected standard block is not found.
            SAPScriptExecutionException: If the file cannot be decoded with
                `encoding`.
            OSError: If an error occurs during file I/O.
        """
        try:
            content = self._read_script_text(script_path, encoding)

            if (
                "sessionIndex = CLng(WScript.Arguments(0))" in content
                and "connectionIndex = CLng(WScript.Arguments(1))" in content
            ):
                return

            if self.SCRIPT_OLD_HEADER not in content:
                raise ValueError(
                    "Standard block not found in script. Is it corrupted?"
                )

            new_content = content.replace(
                self.SCRIPT_OLD_HEADER,
                self.SCRIPT_NEW_HEADER,
                1,
            )
            script_path.write_text(new_content, encoding=encoding)

        except Exception as exc:
            self._logger(
                f"Error updating script header '{script_path}': {exc}",
                True,
            )
            raise

    def _append_excel_close_instruction(self, script_path: Path, encoding: str) -> None:
        """Adds an Excel force-close instruction to the VBS script.

        Args:
            script_path: Path to the VBS script to modify.
            encoding: Text encoding used to read and re-write the script file.

        Raises:
            SAPScriptExecutionException: If the file cannot be decoded with
                `encoding`.
            Exception: Propagates file I/O exceptions after logging.
        """
        try:
            closing_line = (
                'CreateObject("WScript.Shell").Run "taskkill /IM EXCEL.EXE /F", 0, True'
            )
            content = self._read_script_text(script_path, encoding)
            if closing_line in content:
                return
            if content and not content.endswith(("\n", "\r")):
                content += "\r\n"
            content += closing_line
            script_path.write_text(content, encoding=encoding)
        except Exception as exc:
            self._logger(
                f"Error updating script '{script_path}' to disable Excel auto-open: {exc}",
                False
            )
            raise

    def execute(
        self,
        *,
        script_path: Path | str,
        session_index: int,
        connection_index: int,
        script_args: tuple[str, ...] = (),
        timeout: int = 120,
        creates_excel: bool = False,
        created_file_path: Path | str | None = None,
        encoding: str = "utf-16",
    ) -> str:
        """Executes a VBScript targeting a specific SAP session.

        Args:
            script_path: Path to the VBScript file.
            session_index: Index of the target SAP session.
            connection_index: Index of the target SAP connection.
            script_args: Additional arguments for the script.
            timeout: Maximum execution duration in seconds.
            creates_excel: Whether the script manipulates Excel.
            created_file_path: Path to the resulting file (for validation).
            encoding: Text encoding to use when reading/patching this specific
                script file.

        Returns:
            str: Standard output of the script.

        Raises:
            SAPScriptExecutionException: For script errors, timeouts, missing
                files, decode errors under the selected encoding, or if the
                same `script_path` is already being executed concurrently by
                another in-flight call.
        """

        session_key = (connection_index, session_index)
        resolved_script_path = Path(script_path).resolve()

        with self._active_sessions_lock:
            if session_key in self._active_sessions:
                raise SAPScriptExecutionException(
                    f"SAP session ({connection_index}, {session_index}) "
                    "is already in use by another script.",
                    critical=True,
                )
            self._active_sessions.add(session_key)

        with self._active_scripts_lock:
            if resolved_script_path in self._active_scripts:
                with self._active_sessions_lock:
                    self._active_sessions.discard(session_key)
                raise SAPScriptExecutionException(
                    f"Script '{resolved_script_path}' is already being executed "
                    "by another concurrent call (possibly targeting a different "
                    "SAP session). Running the same script file concurrently "
                    "would risk corrupting it during header patching - wait for "
                    "the other execution to finish, or use a separate copy of "
                    "the script per session.",
                    critical=True,
                )
            self._active_scripts.add(resolved_script_path)

        try:
            script_path = Path(script_path)
            created_file = Path(created_file_path) if created_file_path is not None else None

            if not script_path.is_file():
                raise SAPScriptExecutionException(
                    f"Script not found: {script_path}",
                    critical=True,
                )

            self._patch_sap_vbs_script(script_path, encoding)

            if creates_excel and created_file is not None:
                self._append_excel_close_instruction(script_path, encoding)

            result = subprocess.run(
                [
                    "cscript.exe",
                    "//nologo",
                    str(script_path),
                    str(session_index),
                    str(connection_index),
                    *map(str, script_args),
                ],
                capture_output=True,
                text=True,
                timeout=timeout,
                check=False,
            )
        except subprocess.TimeoutExpired as exc:
            raise SAPScriptExecutionException(
                f"Script {script_path} exceeded timeout of {timeout} seconds.",
                critical=True,
            ) from exc
        except SAPScriptExecutionException:
            raise
        except Exception as exc:
            raise SAPScriptExecutionException(
                f"Fatal error during script execution {script_path}: {exc}",
                critical=True,
            ) from exc
        finally:
            with self._active_sessions_lock:
                self._active_sessions.discard(session_key)
            with self._active_scripts_lock:
                self._active_scripts.discard(resolved_script_path)

        stderr = (result.stderr or "").strip()
        if result.returncode != 0 or stderr:
            message = f"Error executing script {script_path} (code={result.returncode})"
            if stderr:
                message += f": {stderr}"

            self._logger(message, True)
            raise SAPScriptExecutionException(message, critical=True)

        self._logger(f"Script executed successfully: {script_path}", False)

        if created_file is not None and self._file_validator is not None:
            self._file_validator(created_file)
            self._logger(f"File validated successfully: {created_file}", False)

        return result.stdout

    def execute_async(self, **kwargs: Any) -> Future[str]:
        """Executes a VBScript in a separate thread.

        Note:
            The concurrent-use-of-the-same-file check (see the class-level
            Warning) is enforced inside `execute`, which runs on the worker
            thread. This means the check happens when the thread pool picks
            up the task, not at the moment `execute_async` is called - if you
            submit many concurrent calls for the same `script_path` faster
            than the pool can start them, only one will proceed at a time and
            the others will fail fast with `SAPScriptExecutionException` as
            soon as they start, rather than silently queuing behind it.

        Returns:
            Future[str]: Future object for the asynchronous result.
        """
        return self._executor.submit(self.execute, **kwargs)

    def shutdown(self) -> None:
        """Gracefully shuts down the thread pool."""
        self._executor.shutdown(wait=True)
